apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ivgitghd
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ivgitghd:763569ad8cf65c16605ffef5528c2c744a098ebe@sha256:8088a8dcb289bbf0e9988fadcda190fb86926fda6bfdd41635988da79c824ec6
          name: container-image
